# This file was generated by GoReleaser. DO NOT EDIT.
cask "wifitui" do
  name "wifitui"
  desc "Connect to known WiFi networks and store profiles, all from the terminal"
  homepage "https://github.com/tonur/wifitui"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wifitui"

  on_macos do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-x86_64.tar.gz"
      sha256 "90f10cc57537eab20c83c0c744f4f23664eb2528039c603afe25b9ae7d9c77ae"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-darwin-arm64.tar.gz"
      sha256 "1e52b6b95fb51508beedb7b2dc4b911f1b7b4ee984581a3afd009511c0bd4a11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-x86_64.tar.gz"
      sha256 "59ee657549227debdfb3956a653cf6ec3267f5246fb2e0d20cdacb1fd6989b3d"
    end
    on_arm do
      url "https://github.com/tonur/wifitui/releases/download/v#{version}/wifitui-#{version}-linux-arm64.tar.gz"
      sha256 "89b65590457ac6c04ad5528def0b84ae7da1350b50833ea49eb42bc06820bb25"
    end
  end

  # No zap stanza required
end
